#!/usr/bin/env python3
"""Run the frozen MRT2 liveness matrix one resumable pair at a time.

The frozen protocol is the source of every experimental value. Existing outputs
are reused only after their paths, hashes, reset counts, frame counts, and pair
invariants validate. The principal ``warm``/``20260718`` arms always point at
the immutable pilot root and are never regenerated by this script.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shlex
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

import numpy as np


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PROTOCOL = REPO_ROOT / "Scratchpad" / "system_paper_liveness" / "protocol.json"
DEFAULT_MATRIX_ROOT = REPO_ROOT / "Scratchpad" / "system_paper_liveness" / "matrix"
DEFAULT_PILOT_ROOT = REPO_ROOT / "Scratchpad" / "system_paper_liveness" / "pilot"
DEFAULT_MODELS_DIR = REPO_ROOT / "Scratchpad" / "system_paper_models"
CROSSOVER = REPO_ROOT / "scripts" / "run_mrt2_long_horizon_crossover.py"
ANALYZER = REPO_ROOT / "scripts" / "analyze_mrt2_liveness.py"
FROZEN_PROTOCOL_SHA256 = (
    "bfd0c7240e07c0f61ed9ee03bde9f07ad6ff4795b7db2c05288c063f1b7253ae"
)
PILOT_PROMPT_ID = "warm"
PILOT_SEED = 20_260_718
RVQ_LEVELS = 12
CODEBOOK_SIZE = 1_024
DECODER_INPUT_FRAMES = 25
DECODER_STRIDE_FRAMES = 24
EXPECTED_DECODER = "mlx-float32-pre-istft-plus-production-rendercore"
EXPECTED_DSP_WINDOW = "trained-periodic-hann"
CODEBOOKS_FILENAME = "spectrostream_rvq_codebooks_12_f32.bin"
RENDER_CORE = REPO_ROOT / "Sources" / "CrossfadeRuntimeCore" / "RenderCore.cpp"
MIN_ORPHAN_AGE_SECONDS = 120.0
REQUIRED_CATASTROPHIC_FLAGS = {
    "unrefreshedNonFiniteToken",
    "unrefreshedNonFinite",
    "unrefreshedDurationMismatch",
    "unrefreshedShorterThan600Seconds",
    "unrefreshedCaptureDiscontinuity",
    "unrefreshedExactRepeated30SecondWindow",
    "unrefreshedIntroducesClipping",
    "unrefreshedChannelCollapseRelativeToRefreshed",
    "unrefreshedExactTokenCycle",
}
REQUIRED_REFERENCE_FLAGS = {
    "refreshedNonFinite",
    "refreshedDurationMismatch",
    "refreshedCaptureDiscontinuity",
}


@dataclass(frozen=True)
class Arm:
    """One generation/decode arm derived from the frozen protocol."""

    arm_id: str
    prompt_id: str
    prompt: str
    seed: int
    mode: str
    refresh_seconds: float
    refresh_frames: int | None
    source_path: Path
    source_sha256: str
    output_dir: Path
    reuse_pilot: bool

    @property
    def manifest_path(self) -> Path:
        """Return the generator manifest path for this arm."""
        return self.output_dir / f"mlx-seed-{self.seed}-manifest.json"

    @property
    def tokens_path(self) -> Path:
        """Return the token-array path for this arm."""
        return self.output_dir / f"mlx-seed-{self.seed}-tokens.npy"

    @property
    def wav_path(self) -> Path:
        """Return the context-12 decoded WAV path for this arm."""
        return self.output_dir / "context12.wav"

    @property
    def decode_report_path(self) -> Path:
        """Return the decoder report path for this arm."""
        return self.wav_path.with_suffix(".json")

    @property
    def context0_wav_path(self) -> Path:
        """Return the neutral-context decoded WAV path for an unrefreshed arm."""
        return self.output_dir / "context0.wav"

    @property
    def context0_decode_report_path(self) -> Path:
        """Return the neutral-context decoder receipt path."""
        return self.context0_wav_path.with_suffix(".json")


@dataclass(frozen=True)
class Pair:
    """Matched refreshed and unrefreshed arms for one prompt and seed."""

    prompt_id: str
    seed: int
    refreshed: Arm
    unrefreshed: Arm
    analysis_dir: Path

    @property
    def analysis_path(self) -> Path:
        """Return the matched-pair analysis report path."""
        return self.analysis_dir / "pair-analysis.json"


@dataclass(frozen=True)
class Matrix:
    """Validated protocol values and their derived execution pairs."""

    protocol_path: Path
    protocol_sha256: str
    checkpoint_path: Path
    checkpoint_sha256: str
    seconds: int
    expected_frames: int
    temperature: float
    top_k: int
    decoder_context_frames: int
    arms: tuple[Arm, ...]
    pairs: tuple[Pair, ...]


def _sha256(path: Path) -> str:
    """Return the lowercase SHA-256 digest of ``path``."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _load_json(path: Path) -> dict[str, Any]:
    """Load a JSON object and reject every other top-level type."""
    value = json.loads(path.read_text())
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def _repo_path(value: str | Path) -> Path:
    """Resolve a protocol or artifact path relative to the repository."""
    path = Path(value)
    return path if path.is_absolute() else REPO_ROOT / path


def _require_file_hash(path: Path, expected: object, label: str) -> None:
    """Require an existing file whose bytes match ``expected``."""
    if not path.is_file():
        raise ValueError(f"missing {label}: {path}")
    actual = _sha256(path)
    if not isinstance(expected, str) or actual != expected:
        raise ValueError(
            f"{label} hash mismatch: {path} has {actual}, expected {expected}"
        )


def _require_equal(actual: object, expected: object, label: str) -> None:
    """Raise a stable validation error when two protocol values differ."""
    if actual != expected:
        raise ValueError(f"{label}={actual!r}, expected {expected!r}")


def load_matrix(
    protocol_path: Path,
    *,
    matrix_root: Path,
    pilot_root: Path,
    expected_protocol_sha256: str,
) -> Matrix:
    """Load and fail-closed validate the frozen factorial protocol."""
    protocol_path = protocol_path.resolve()
    _require_file_hash(protocol_path, expected_protocol_sha256, "frozen protocol")
    protocol = _load_json(protocol_path)
    _require_equal(
        protocol.get("schema"), "mrt2-liveness-protocol-v1", "protocol schema"
    )
    _require_equal(
        protocol.get("status"),
        "frozen-before-candidate-generation",
        "protocol status",
    )

    generation = protocol.get("generation")
    if not isinstance(generation, dict):
        raise ValueError("protocol generation must be an object")
    seconds = generation.get("audibleSeconds")
    expected_frames = generation.get("expectedTokenFramesIncludingLookahead")
    temperature = generation.get("temperature")
    top_k = generation.get("topK")
    decoder_context = generation.get("decoderContextFrames")
    if not isinstance(seconds, int) or seconds <= 0:
        raise ValueError("protocol audibleSeconds must be a positive integer")
    if expected_frames != seconds * 25 + 1:
        raise ValueError("protocol expected token frames do not match 25 Hz")
    if not isinstance(temperature, (int, float)) or temperature <= 0:
        raise ValueError("protocol temperature must be positive")
    _require_equal(top_k, 40, "protocol topK")
    _require_equal(decoder_context, 12, "protocol decoderContextFrames")

    checkpoint = protocol.get("checkpoint")
    if not isinstance(checkpoint, dict):
        raise ValueError("protocol checkpoint must be an object")
    checkpoint_path = _repo_path(checkpoint.get("path", ""))
    checkpoint_sha256 = checkpoint.get("sha256")
    _require_file_hash(checkpoint_path, checkpoint_sha256, "checkpoint")

    fixtures_value = protocol.get("fixtures")
    if not isinstance(fixtures_value, list) or not fixtures_value:
        raise ValueError("protocol fixtures must be a nonempty list")
    if len(fixtures_value) != 4:
        raise ValueError("frozen protocol must contain exactly four fixtures")
    fixtures: dict[str, dict[str, Any]] = {}
    for fixture in fixtures_value:
        if not isinstance(fixture, dict) or not isinstance(fixture.get("id"), str):
            raise ValueError("every protocol fixture must have a string id")
        fixture_id = fixture["id"]
        if fixture_id in fixtures:
            raise ValueError(f"duplicate protocol fixture: {fixture_id}")
        source = fixture.get("sourceConditioning")
        if not isinstance(source, dict):
            raise ValueError(f"fixture {fixture_id} lacks source conditioning")
        source_path = _repo_path(source.get("path", ""))
        _require_file_hash(
            source_path, source.get("sha256"), f"{fixture_id} conditioning"
        )
        fixtures[fixture_id] = fixture

    modes_value = protocol.get("refreshModes")
    if not isinstance(modes_value, list):
        raise ValueError("protocol refreshModes must be a list")
    modes = {mode.get("id"): mode for mode in modes_value if isinstance(mode, dict)}
    _require_equal(set(modes), {"refresh10", "unrefreshed"}, "refresh modes")
    _require_equal(modes["refresh10"].get("refreshFrames"), 250, "refresh10 frames")
    _require_equal(
        modes["unrefreshed"].get("refreshFrames"), None, "unrefreshed frames"
    )

    seeds_value = protocol.get("seeds")
    if not isinstance(seeds_value, list) or not all(
        isinstance(seed, int) for seed in seeds_value
    ):
        raise ValueError("protocol seeds must be integers")
    seeds = tuple(seeds_value)
    if len(set(seeds)) != len(seeds):
        raise ValueError("protocol seeds must be unique")
    if len(seeds) != 3:
        raise ValueError("frozen protocol must contain exactly three seeds")

    arms_value = protocol.get("arms")
    if not isinstance(arms_value, list):
        raise ValueError("protocol arms must be a list")
    expected_keys = {
        (fixture_id, seed, mode_id)
        for fixture_id in fixtures
        for seed in seeds
        for mode_id in modes
    }
    raw_by_key: dict[tuple[str, int, str], dict[str, Any]] = {}
    for raw in arms_value:
        if not isinstance(raw, dict):
            raise ValueError("protocol arm must be an object")
        key = (raw.get("promptId"), raw.get("seed"), raw.get("mode"))
        if key in raw_by_key:
            raise ValueError(f"duplicate protocol arm: {key}")
        raw_by_key[key] = raw
    _require_equal(set(raw_by_key), expected_keys, "factorial arm keys")

    arms: list[Arm] = []
    arm_by_key: dict[tuple[str, int, str], Arm] = {}
    for fixture_id in fixtures:
        fixture = fixtures[fixture_id]
        source = fixture["sourceConditioning"]
        for seed in seeds:
            for mode_id in ("refresh10", "unrefreshed"):
                raw = raw_by_key[(fixture_id, seed, mode_id)]
                mode = modes[mode_id]
                _require_equal(
                    raw.get("sourceConditioningSha256"),
                    source.get("sha256"),
                    f"{raw.get('armId')} source hash",
                )
                _require_equal(
                    raw.get("refreshSeconds"),
                    mode.get("refreshSeconds"),
                    f"{raw.get('armId')} refresh seconds",
                )
                reuse_pilot = fixture_id == PILOT_PROMPT_ID and seed == PILOT_SEED
                output_dir = (
                    pilot_root / mode_id
                    if reuse_pilot
                    else matrix_root / fixture_id / f"seed-{seed}" / mode_id
                )
                arm = Arm(
                    arm_id=raw["armId"],
                    prompt_id=fixture_id,
                    prompt=fixture["prompt"],
                    seed=seed,
                    mode=mode_id,
                    refresh_seconds=float(mode["refreshSeconds"]),
                    refresh_frames=mode.get("refreshFrames"),
                    source_path=_repo_path(source["path"]),
                    source_sha256=source["sha256"],
                    output_dir=output_dir,
                    reuse_pilot=reuse_pilot,
                )
                arms.append(arm)
                arm_by_key[(fixture_id, seed, mode_id)] = arm

    pairs = tuple(
        Pair(
            prompt_id=fixture_id,
            seed=seed,
            refreshed=arm_by_key[(fixture_id, seed, "refresh10")],
            unrefreshed=arm_by_key[(fixture_id, seed, "unrefreshed")],
            analysis_dir=(
                pilot_root / "analysis-full-capture"
                if fixture_id == PILOT_PROMPT_ID and seed == PILOT_SEED
                else matrix_root / fixture_id / f"seed-{seed}" / "analysis"
            ),
        )
        for fixture_id in fixtures
        for seed in seeds
    )
    return Matrix(
        protocol_path=protocol_path,
        protocol_sha256=expected_protocol_sha256,
        checkpoint_path=checkpoint_path,
        checkpoint_sha256=checkpoint_sha256,
        seconds=seconds,
        expected_frames=expected_frames,
        temperature=float(temperature),
        top_k=top_k,
        decoder_context_frames=decoder_context,
        arms=tuple(arms),
        pairs=pairs,
    )


def generation_command(matrix: Matrix, arm: Arm) -> list[str]:
    """Build the exact MLX generation command for ``arm``."""
    return [
        sys.executable,
        str(CROSSOVER),
        "generate-mlx",
        "--seconds",
        str(matrix.seconds),
        "--seed",
        str(arm.seed),
        "--refresh-seconds",
        str(arm.refresh_seconds),
        "--prompt",
        arm.prompt,
        "--source-conditioning",
        str(arm.source_path),
        "--checkpoint",
        str(matrix.checkpoint_path),
        "--temperature",
        str(matrix.temperature),
        "--top-k",
        str(matrix.top_k),
        "--output-dir",
        str(arm.output_dir),
    ]


def _decode_command(
    matrix: Matrix,
    arm: Arm,
    models_dir: Path,
    *,
    context_frames: int,
    output_wav: Path,
) -> list[str]:
    """Build one production-DSP decode command for an explicit context."""
    return [
        sys.executable,
        str(CROSSOVER),
        "decode-mlx-stft-core-dsp",
        "--tokens",
        str(arm.tokens_path),
        "--output-wav",
        str(output_wav),
        "--decoder-context-frames",
        str(context_frames),
        "--models-dir",
        str(models_dir),
        "--checkpoint",
        str(matrix.checkpoint_path),
    ]


def decode_command(matrix: Matrix, arm: Arm, models_dir: Path) -> list[str]:
    """Build the context-12 production-DSP decode command for ``arm``."""
    return _decode_command(
        matrix,
        arm,
        models_dir,
        context_frames=matrix.decoder_context_frames,
        output_wav=arm.wav_path,
    )


def context0_decode_command(
    matrix: Matrix, arm: Arm, models_dir: Path
) -> list[str]:
    """Build the neutral-context production-DSP decode command for ``arm``."""
    if arm.mode != "unrefreshed":
        raise ValueError(f"{arm.arm_id} is not an unrefreshed arm")
    return _decode_command(
        matrix,
        arm,
        models_dir,
        context_frames=0,
        output_wav=arm.context0_wav_path,
    )


def analysis_command(matrix: Matrix, pair: Pair) -> list[str]:
    """Build the frozen matched-pair analysis command for ``pair``."""
    return [
        sys.executable,
        str(ANALYZER),
        "--protocol",
        str(matrix.protocol_path),
        "--refreshed-manifest",
        str(pair.refreshed.manifest_path),
        "--unrefreshed-manifest",
        str(pair.unrefreshed.manifest_path),
        "--refreshed-wav",
        str(pair.refreshed.wav_path),
        "--unrefreshed-wav",
        str(pair.unrefreshed.wav_path),
        "--output-dir",
        str(pair.analysis_dir),
    ]


def _validate_hash_record(
    value: object,
    *,
    expected_path: Path,
    expected_sha256: str,
    label: str,
) -> None:
    """Validate a manifest ``{path, sha256}`` record and its bytes."""
    if not isinstance(value, dict):
        raise ValueError(f"{label} must be a path/hash object")
    actual_path = _repo_path(value.get("path", ""))
    if actual_path.resolve() != expected_path.resolve():
        raise ValueError(f"{label} path mismatch: {actual_path} != {expected_path}")
    _require_equal(value.get("sha256"), expected_sha256, f"{label} recorded hash")
    _require_file_hash(actual_path, expected_sha256, label)


def validate_arm(matrix: Matrix, arm: Arm) -> dict[str, Any]:
    """Validate a completed generation arm against the frozen protocol."""
    manifest = _load_json(arm.manifest_path)
    expected_mode = "periodic" if arm.mode == "refresh10" else "off"
    expected_resets = (
        (matrix.expected_frames - 1) // arm.refresh_frames
        if arm.refresh_frames is not None
        else 0
    )
    expected_values = {
        "schema": "mrt2-long-horizon-token-run-v1",
        "tokenSource": "mlx",
        "seed": arm.seed,
        "prompt": arm.prompt,
        "temperature": matrix.temperature,
        "topK": matrix.top_k,
        "trajectoryRefreshSeconds": arm.refresh_seconds,
        "refreshMode": expected_mode,
        "temporalResetCount": expected_resets,
        "requestedAudibleSeconds": matrix.seconds,
        "tokenFrames": matrix.expected_frames,
    }
    for key, expected in expected_values.items():
        _require_equal(manifest.get(key), expected, f"{arm.arm_id} {key}")

    inputs = manifest.get("inputs")
    if not isinstance(inputs, dict):
        raise ValueError(f"{arm.arm_id} inputs must be an object")
    _validate_hash_record(
        inputs.get("checkpoint"),
        expected_path=matrix.checkpoint_path,
        expected_sha256=matrix.checkpoint_sha256,
        label=f"{arm.arm_id} checkpoint",
    )
    _validate_hash_record(
        inputs.get("sourceConditioning"),
        expected_path=arm.source_path,
        expected_sha256=arm.source_sha256,
        label=f"{arm.arm_id} conditioning",
    )

    token_record = manifest.get("tokens")
    if not isinstance(token_record, dict):
        raise ValueError(f"{arm.arm_id} tokens must be a path/hash object")
    token_sha256 = _sha256(arm.tokens_path)
    _validate_hash_record(
        token_record,
        expected_path=arm.tokens_path,
        expected_sha256=token_sha256,
        label=f"{arm.arm_id} tokens",
    )
    tokens = np.load(arm.tokens_path, mmap_mode="r", allow_pickle=False)
    _require_equal(
        tuple(tokens.shape),
        (matrix.expected_frames, RVQ_LEVELS),
        f"{arm.arm_id} token shape",
    )
    if not np.issubdtype(tokens.dtype, np.integer):
        raise ValueError(f"{arm.arm_id} tokens are not integers")
    if int(np.min(tokens)) < 0 or int(np.max(tokens)) >= CODEBOOK_SIZE:
        raise ValueError(f"{arm.arm_id} tokens are outside 0..{CODEBOOK_SIZE - 1}")

    summary_record = manifest.get("summary")
    if not isinstance(summary_record, dict):
        raise ValueError(f"{arm.arm_id} summary must be a path/hash object")
    summary_path = _repo_path(summary_record.get("path", ""))
    _require_file_hash(
        summary_path, summary_record.get("sha256"), f"{arm.arm_id} summary"
    )
    summary = _load_json(summary_path)
    _require_equal(
        summary.get("schema"),
        "mrt2-token-trajectory-summary-v1",
        f"{arm.arm_id} summary schema",
    )
    _require_equal(
        summary.get("frames"), matrix.expected_frames, f"{arm.arm_id} summary frames"
    )
    return manifest


def _validate_decode(
    matrix: Matrix,
    arm: Arm,
    *,
    context_frames: int,
    wav_path: Path,
    report_path: Path,
    models_dir: Path,
) -> dict[str, Any]:
    """Validate one decoded WAV and receipt against an explicit context."""
    report = _load_json(report_path)
    label = f"{arm.arm_id} context-{context_frames}"
    _require_equal(
        report.get("schema"), "mrt2-crossover-decode-v1", f"{label} decode schema"
    )
    _require_equal(
        report.get("decoderContextFrames"),
        context_frames,
        f"{label} decoder context",
    )
    _require_equal(
        report.get("decoder"), EXPECTED_DECODER, f"{label} decoder implementation"
    )
    expected_stride = DECODER_STRIDE_FRAMES - context_frames
    _require_equal(
        report.get("decoderStrideFrames"),
        expected_stride,
        f"{label} decoder stride",
    )
    _require_equal(
        report.get("dspWindow"), EXPECTED_DSP_WINDOW, f"{label} DSP window"
    )
    _require_equal(
        _repo_path(report.get("tokenPath", "")).resolve(),
        arm.tokens_path.resolve(),
        f"{label} decode token path",
    )
    _require_equal(
        report.get("tokenSha256"),
        _sha256(arm.tokens_path),
        f"{label} decode token hash",
    )
    _require_equal(
        report.get("checkpointSha256"),
        matrix.checkpoint_sha256,
        f"{label} decode checkpoint hash",
    )
    _require_equal(
        report.get("renderedFrames"),
        matrix.seconds * 48_000,
        f"{label} rendered frames",
    )
    _require_equal(
        report.get("durationSeconds"),
        float(matrix.seconds),
        f"{label} decode duration",
    )
    expected_windows = (
        matrix.expected_frames - DECODER_INPUT_FRAMES
    ) // expected_stride + 1
    _require_equal(
        report.get("windows"), expected_windows, f"{label} decoder windows"
    )
    codebooks_path = models_dir / CODEBOOKS_FILENAME
    _require_file_hash(
        codebooks_path, report.get("codebooksSha256"), f"{label} codebooks"
    )
    _require_file_hash(
        RENDER_CORE, report.get("renderCoreSha256"), f"{label} RenderCore"
    )
    wav_sha256 = _sha256(wav_path)
    _validate_hash_record(
        report.get("wav"),
        expected_path=wav_path,
        expected_sha256=wav_sha256,
        label=f"{label} wav",
    )
    return report


def validate_decode(
    matrix: Matrix, arm: Arm, *, models_dir: Path = DEFAULT_MODELS_DIR
) -> dict[str, Any]:
    """Validate one context-12 decoded WAV and its report."""
    return _validate_decode(
        matrix,
        arm,
        context_frames=matrix.decoder_context_frames,
        wav_path=arm.wav_path,
        report_path=arm.decode_report_path,
        models_dir=models_dir,
    )


def validate_context0_decode(
    matrix: Matrix, arm: Arm, *, models_dir: Path = DEFAULT_MODELS_DIR
) -> dict[str, Any]:
    """Validate the neutral-context decode required for an unrefreshed arm."""
    if arm.mode != "unrefreshed":
        raise ValueError(f"{arm.arm_id} is not an unrefreshed arm")
    return _validate_decode(
        matrix,
        arm,
        context_frames=0,
        wav_path=arm.context0_wav_path,
        report_path=arm.context0_decode_report_path,
        models_dir=models_dir,
    )


def validate_analysis(
    matrix: Matrix, pair: Pair, *, models_dir: Path = DEFAULT_MODELS_DIR
) -> dict[str, Any]:
    """Validate a pair report against its exact inputs and protocol."""
    report = _load_json(pair.analysis_path)
    _require_equal(
        report.get("schema"),
        "mrt2-liveness-pair-analysis-v1",
        f"{pair.prompt_id}/{pair.seed} analysis schema",
    )
    _require_equal(
        report.get("protocolSha256"),
        matrix.protocol_sha256,
        f"{pair.prompt_id}/{pair.seed} protocol hash",
    )
    _require_equal(
        report.get("promptId"), pair.prompt_id, f"{pair.prompt_id}/{pair.seed} promptId"
    )
    _require_equal(
        report.get("seed"), pair.seed, f"{pair.prompt_id}/{pair.seed} report seed"
    )
    _require_equal(
        report.get("armIds"),
        {
            "refreshed": pair.refreshed.arm_id,
            "unrefreshed": pair.unrefreshed.arm_id,
        },
        f"{pair.prompt_id}/{pair.seed} arm IDs",
    )
    manifests = report.get("manifests")
    wavs = report.get("wavs")
    decode_receipts = report.get("decodeReceipts")
    if (
        not isinstance(manifests, dict)
        or not isinstance(wavs, dict)
        or not isinstance(decode_receipts, dict)
    ):
        raise ValueError(f"{pair.prompt_id}/{pair.seed} analysis inputs are missing")
    for label, arm in (
        ("refreshed", pair.refreshed),
        ("unrefreshed", pair.unrefreshed),
    ):
        validate_decode(matrix, arm, models_dir=models_dir)
        _validate_hash_record(
            manifests.get(label),
            expected_path=arm.manifest_path,
            expected_sha256=_sha256(arm.manifest_path),
            label=f"{pair.prompt_id}/{pair.seed} {label} manifest",
        )
        _validate_hash_record(
            wavs.get(label),
            expected_path=arm.wav_path,
            expected_sha256=_sha256(arm.wav_path),
            label=f"{pair.prompt_id}/{pair.seed} {label} wav",
        )
        _validate_hash_record(
            decode_receipts.get(label),
            expected_path=arm.decode_report_path,
            expected_sha256=_sha256(arm.decode_report_path),
            label=f"{pair.prompt_id}/{pair.seed} {label} decode receipt",
        )
    invariants = report.get("pairInvariants")
    if not isinstance(invariants, dict):
        raise ValueError(f"{pair.prompt_id}/{pair.seed} pair invariants are missing")
    _require_equal(
        invariants.get("seed"), pair.seed, f"{pair.prompt_id}/{pair.seed} seed"
    )
    _require_equal(
        invariants.get("prompt"),
        pair.refreshed.prompt,
        f"{pair.prompt_id}/{pair.seed} prompt",
    )
    _require_equal(
        invariants.get("tokenFrames"),
        matrix.expected_frames,
        f"{pair.prompt_id}/{pair.seed} frames",
    )
    full_capture = report.get("fullCapture")
    if not isinstance(full_capture, dict) or set(full_capture) != {
        "refreshed",
        "unrefreshed",
    }:
        raise ValueError(
            f"{pair.prompt_id}/{pair.seed} full-capture evidence is missing"
        )
    for label in ("refreshed", "unrefreshed"):
        capture = full_capture[label]
        if not isinstance(capture, dict):
            raise ValueError(
                f"{pair.prompt_id}/{pair.seed} {label} full capture is invalid"
            )
        required_capture = {
            "readFrames",
            "finiteRatio",
            "exactExpectedDuration",
            "captureDiscontinuityDetected",
        }
        if not required_capture.issubset(capture):
            raise ValueError(
                f"{pair.prompt_id}/{pair.seed} {label} full capture is incomplete"
            )

    catastrophic = report.get("catastrophicIntegrityFailures")
    reference = report.get("refreshedReferenceIntegrityFailures")
    status = report.get("catastrophicIntegrityStatus")
    if (
        not isinstance(catastrophic, dict)
        or set(catastrophic) != REQUIRED_CATASTROPHIC_FLAGS
    ):
        raise ValueError(
            f"{pair.prompt_id}/{pair.seed} catastrophic flags are incomplete"
        )
    if not isinstance(reference, dict) or set(reference) != REQUIRED_REFERENCE_FLAGS:
        raise ValueError(f"{pair.prompt_id}/{pair.seed} reference flags are incomplete")
    if not all(
        isinstance(value, bool)
        for value in (*catastrophic.values(), *reference.values())
    ):
        raise ValueError(
            f"{pair.prompt_id}/{pair.seed} integrity flags must be boolean"
        )
    if not isinstance(status, dict) or status.get("allChecksAssessed") is not True:
        raise ValueError(
            f"{pair.prompt_id}/{pair.seed} integrity status is not fully assessed"
        )
    candidate_failures = sorted(key for key, value in catastrophic.items() if value)
    reference_failures = sorted(key for key, value in reference.items() if value)
    all_failures = reference_failures + candidate_failures
    expected_status = {
        "verdict": "fail" if all_failures else "pass",
        "passed": not all_failures,
        "failureIds": all_failures,
        "candidateFailureIds": candidate_failures,
        "referenceFailureIds": reference_failures,
        "allChecksAssessed": True,
    }
    _require_equal(
        status, expected_status, f"{pair.prompt_id}/{pair.seed} integrity status"
    )
    return report


def _probe(path: Path, validator: Callable[[], object]) -> dict[str, Any]:
    """Return a status row without weakening validation failures."""
    if not path.is_file():
        return {"state": "missing", "path": str(path)}
    try:
        validator()
    except (KeyError, OSError, TypeError, ValueError) as error:
        return {"state": "invalid", "path": str(path), "error": str(error)}
    return {"state": "complete", "path": str(path)}


def matrix_status(
    matrix: Matrix, *, models_dir: Path = DEFAULT_MODELS_DIR
) -> dict[str, Any]:
    """Return fail-closed completion status for every arm and pair."""
    arms = []
    for arm in matrix.arms:
        context0 = (
            _probe(
                arm.context0_decode_report_path,
                lambda arm=arm: validate_context0_decode(
                    matrix, arm, models_dir=models_dir
                ),
            )
            if arm.mode == "unrefreshed"
            else {"state": "not-applicable"}
        )
        arms.append(
            {
                "armId": arm.arm_id,
                "reusePilot": arm.reuse_pilot,
                "generation": _probe(
                    arm.manifest_path, lambda arm=arm: validate_arm(matrix, arm)
                ),
                "decode": _probe(
                    arm.decode_report_path,
                    lambda arm=arm: validate_decode(matrix, arm, models_dir=models_dir),
                ),
                "context0Decode": context0,
            }
        )
    pairs = [
        {
            "promptId": pair.prompt_id,
            "seed": pair.seed,
            "analysis": _probe(
                pair.analysis_path,
                lambda pair=pair: validate_analysis(
                    matrix, pair, models_dir=models_dir
                ),
            ),
        }
        for pair in matrix.pairs
    ]
    return {
        "schema": "mrt2-liveness-matrix-status-v1",
        "protocolSha256": matrix.protocol_sha256,
        "arms": arms,
        "pairs": pairs,
        "complete": all(
            row[phase]["state"] == "complete"
            for row in arms
            for phase in ("generation", "decode")
        )
        and all(
            row["context0Decode"]["state"] == "complete"
            for row in arms
            if row["context0Decode"]["state"] != "not-applicable"
        )
        and all(row["analysis"]["state"] == "complete" for row in pairs),
    }


def list_matrix(matrix: Matrix) -> dict[str, Any]:
    """Return the immutable execution inventory without inspecting outputs."""
    return {
        "schema": "mrt2-liveness-matrix-list-v1",
        "protocol": str(matrix.protocol_path),
        "protocolSha256": matrix.protocol_sha256,
        "arms": [
            {
                "armId": arm.arm_id,
                "promptId": arm.prompt_id,
                "seed": arm.seed,
                "mode": arm.mode,
                "reusePilot": arm.reuse_pilot,
                "outputDir": str(arm.output_dir),
                "context12Wav": str(arm.wav_path),
                "context0Wav": (
                    str(arm.context0_wav_path)
                    if arm.mode == "unrefreshed"
                    else None
                ),
            }
            for arm in matrix.arms
        ],
        "pairs": [
            {
                "promptId": pair.prompt_id,
                "seed": pair.seed,
                "analysisDir": str(pair.analysis_dir),
            }
            for pair in matrix.pairs
        ],
    }


def _ensure_no_partial_generation(arm: Arm) -> None:
    """Refuse to overwrite orphaned generation products."""
    partial = [
        path
        for path in (
            arm.tokens_path,
            arm.output_dir / f"mlx-seed-{arm.seed}-token-summary.json",
        )
        if path.exists()
    ]
    if partial:
        raise ValueError(
            f"{arm.arm_id} has partial generation outputs without a manifest: {partial}"
        )


def _decode_paths(arm: Arm, context_frames: int) -> tuple[Path, Path]:
    """Return the WAV and receipt paths for one supported decode context."""
    if context_frames == 0:
        if arm.mode != "unrefreshed":
            raise ValueError(f"{arm.arm_id} is not an unrefreshed arm")
        return arm.context0_wav_path, arm.context0_decode_report_path
    if context_frames == 12:
        return arm.wav_path, arm.decode_report_path
    raise ValueError(f"unsupported decoder context: {context_frames}")


def _orphan_decode_destination(arm: Arm, context_frames: int = 12) -> Path:
    """Return a content-addressed quarantine path for an orphan decoded WAV."""
    wav_path, _ = _decode_paths(arm, context_frames)
    digest = _sha256(wav_path)
    return (
        arm.output_dir
        / "orphaned"
        / f"context{context_frames}.orphan-{digest[:16]}.wav"
    )


def _require_old_orphan_decode(arm: Arm, context_frames: int = 12) -> Path:
    """Validate that an orphan WAV is old enough to be safely quarantined."""
    wav_path, report_path = _decode_paths(arm, context_frames)
    if not wav_path.is_file() or report_path.exists():
        raise ValueError(
            f"{arm.arm_id} does not have a context-{context_frames} orphan WAV to repair"
        )
    age = time.time() - wav_path.stat().st_mtime
    if age < MIN_ORPHAN_AGE_SECONDS:
        raise ValueError(
            f"{arm.arm_id} orphan WAV is only {age:.1f}s old; wait at least "
            f"{MIN_ORPHAN_AGE_SECONDS:.0f}s to avoid moving an active decode"
        )
    destination = _orphan_decode_destination(arm, context_frames)
    if destination.exists():
        raise ValueError(
            f"{arm.arm_id} quarantine destination already exists: {destination}"
        )
    return destination


def quarantine_orphan_decode(arm: Arm, context_frames: int = 12) -> Path:
    """Move an old receipt-less WAV to recoverable content-addressed quarantine."""
    wav_path, _ = _decode_paths(arm, context_frames)
    destination = _require_old_orphan_decode(arm, context_frames)
    destination.parent.mkdir(parents=True, exist_ok=True)
    wav_path.rename(destination)
    return destination


def _plan_decode(
    matrix: Matrix,
    arm: Arm,
    *,
    models_dir: Path,
    context_frames: int,
    repair_partials: bool,
) -> list[dict[str, Any]]:
    """Validate or plan one decode, including recoverable orphan handling."""
    wav_path, report_path = _decode_paths(arm, context_frames)
    validator = validate_context0_decode if context_frames == 0 else validate_decode
    command_builder = context0_decode_command if context_frames == 0 else decode_command
    step_name = "decode-context0" if context_frames == 0 else "decode"
    if report_path.is_file():
        validator(matrix, arm, models_dir=models_dir)
        return []
    steps: list[dict[str, Any]] = []
    if wav_path.exists():
        if not repair_partials:
            raise ValueError(
                f"{arm.arm_id} has a context-{context_frames} WAV without a decode "
                f"report: {wav_path}; rerun with --repair-partials to quarantine an "
                "old orphan"
            )
        destination = _require_old_orphan_decode(arm, context_frames)
        steps.append(
            {
                "step": "quarantine-decode-partial",
                "armId": arm.arm_id,
                "contextFrames": context_frames,
                "source": str(wav_path),
                "destination": str(destination),
            }
        )
    command = command_builder(matrix, arm, models_dir)
    steps.append(
        {
            "step": step_name,
            "armId": arm.arm_id,
            "contextFrames": context_frames,
            "command": command,
            "shell": shlex.join(command),
        }
    )
    return steps


def _run_decode(
    matrix: Matrix,
    arm: Arm,
    *,
    models_dir: Path,
    context_frames: int,
    repair_partials: bool,
) -> None:
    """Validate or execute one decode with resumable orphan recovery."""
    wav_path, report_path = _decode_paths(arm, context_frames)
    validator = validate_context0_decode if context_frames == 0 else validate_decode
    command_builder = context0_decode_command if context_frames == 0 else decode_command
    if report_path.is_file():
        validator(matrix, arm, models_dir=models_dir)
        return
    if wav_path.exists():
        if not repair_partials:
            raise ValueError(
                f"{arm.arm_id} has a context-{context_frames} WAV without a decode "
                f"report: {wav_path}; rerun with --repair-partials to quarantine an "
                "old orphan"
            )
        destination = quarantine_orphan_decode(arm, context_frames)
        print(f"quarantined {wav_path} -> {destination}", flush=True)
    _run_command(command_builder(matrix, arm, models_dir))
    validator(matrix, arm, models_dir=models_dir)


def planned_steps(
    matrix: Matrix, *, models_dir: Path, repair_partials: bool = False
) -> list[dict[str, Any]]:
    """Return commands for every missing step without running them."""
    steps: list[dict[str, Any]] = []
    for pair in matrix.pairs:
        for arm in (pair.refreshed, pair.unrefreshed):
            if arm.manifest_path.is_file():
                validate_arm(matrix, arm)
            elif arm.reuse_pilot:
                raise ValueError(f"required pilot arm is missing: {arm.manifest_path}")
            else:
                _ensure_no_partial_generation(arm)
                command = generation_command(matrix, arm)
                steps.append(
                    {
                        "step": "generate",
                        "armId": arm.arm_id,
                        "command": command,
                        "shell": shlex.join(command),
                    }
                )
            steps.extend(
                _plan_decode(
                    matrix,
                    arm,
                    models_dir=models_dir,
                    context_frames=matrix.decoder_context_frames,
                    repair_partials=repair_partials,
                )
            )
            if arm.mode == "unrefreshed":
                steps.extend(
                    _plan_decode(
                        matrix,
                        arm,
                        models_dir=models_dir,
                        context_frames=0,
                        repair_partials=repair_partials,
                    )
                )
        if pair.analysis_path.is_file():
            validate_analysis(matrix, pair, models_dir=models_dir)
        else:
            command = analysis_command(matrix, pair)
            steps.append(
                {
                    "step": "analyze",
                    "pair": f"{pair.prompt_id}/seed-{pair.seed}",
                    "command": command,
                    "shell": shlex.join(command),
                }
            )
    return steps


def _run_command(command: list[str]) -> None:
    """Print and execute one command without invoking a shell."""
    print(shlex.join(command), flush=True)
    subprocess.run(command, cwd=REPO_ROOT, check=True)


def run_matrix(
    matrix: Matrix, *, models_dir: Path, repair_partials: bool = False
) -> None:
    """Run every missing arm, decode, and pair analysis sequentially."""
    for pair in matrix.pairs:
        for arm in (pair.refreshed, pair.unrefreshed):
            if arm.manifest_path.is_file():
                validate_arm(matrix, arm)
            elif arm.reuse_pilot:
                raise ValueError(f"required pilot arm is missing: {arm.manifest_path}")
            else:
                _ensure_no_partial_generation(arm)
                _run_command(generation_command(matrix, arm))
                validate_arm(matrix, arm)
            _run_decode(
                matrix,
                arm,
                models_dir=models_dir,
                context_frames=matrix.decoder_context_frames,
                repair_partials=repair_partials,
            )
            if arm.mode == "unrefreshed":
                _run_decode(
                    matrix,
                    arm,
                    models_dir=models_dir,
                    context_frames=0,
                    repair_partials=repair_partials,
                )
        if pair.analysis_path.is_file():
            validate_analysis(matrix, pair, models_dir=models_dir)
        else:
            _run_command(analysis_command(matrix, pair))
            validate_analysis(matrix, pair, models_dir=models_dir)


def parse_args() -> argparse.Namespace:
    """Parse matrix orchestration commands and shared paths."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("run", "dry-run", "list", "status"))
    parser.add_argument("--protocol", type=Path, default=DEFAULT_PROTOCOL)
    parser.add_argument("--matrix-root", type=Path, default=DEFAULT_MATRIX_ROOT)
    parser.add_argument("--pilot-root", type=Path, default=DEFAULT_PILOT_ROOT)
    parser.add_argument("--models-dir", type=Path, default=DEFAULT_MODELS_DIR)
    parser.add_argument("--expected-protocol-sha256", default=FROZEN_PROTOCOL_SHA256)
    parser.add_argument(
        "--repair-partials",
        action="store_true",
        help=(
            "quarantine receipt-less decoded WAVs older than two minutes before "
            "rerunning them; default behavior remains fail-closed"
        ),
    )
    return parser.parse_args()


def main() -> None:
    """Inspect, plan, or execute the resumable frozen matrix."""
    args = parse_args()
    matrix = load_matrix(
        args.protocol,
        matrix_root=args.matrix_root,
        pilot_root=args.pilot_root,
        expected_protocol_sha256=args.expected_protocol_sha256,
    )
    if args.command == "list":
        result = list_matrix(matrix)
    elif args.command == "status":
        result = matrix_status(matrix, models_dir=args.models_dir)
    elif args.command == "dry-run":
        result = {
            "schema": "mrt2-liveness-matrix-plan-v1",
            "protocolSha256": matrix.protocol_sha256,
            "steps": planned_steps(
                matrix,
                models_dir=args.models_dir,
                repair_partials=args.repair_partials,
            ),
        }
    else:
        run_matrix(
            matrix,
            models_dir=args.models_dir,
            repair_partials=args.repair_partials,
        )
        result = matrix_status(matrix, models_dir=args.models_dir)
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
